spring:
  application:
    name: CourseReportGeneration
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      keepalive-time: 100000
      minimum-idle: 10
    password: venu90
    url: jdbc:mysql:///teamplayer
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    show-sql: true

#  sql:
#   init:
#     mode: always
  